### ISSUE TITLE
UTF-8 encoding

### ISSUE THREAD

**Issue by Chklang** [artifacthealth/typedoc-plantuml#4]
Hi

I'm french so i've many special caracters like "é", "à", etc... so my diagrams are in UTF-8 encoding.
If i go to watch the "node-plantuml" plugin, function "generate", i can see :

`module.exports.generate = function (input, options, callback) {`

And these options are directly given to java command. So i must give "-charset UTF-8" to "options" parameter.

If i watch your code, in "writeLocalImage()" function, you call generate without any option :

`var gen = plantuml.generate({format: format});`

Can you add options to your plugin to give some parameters to plantuml converter?

Regards.

**Comment by meirgottlieb** [comment]
The issue was in the [plantuml-encoder](https://github.com/markushedvall/plantuml-encoder/blob/master/lib/plantuml-encoder.js) module I was using. It had this line that was causing the problem:

```  
var utf8 = unescape(encodeURIComponent(text))
```

They do the same thing in the Plantuml Javascript example source code. Anyways, I removed the dependency on that module and just do the encoding myself without that line and the image generation with special characters now seems to work fine.
